- |
  cat <<EOF >/etc/nomad.d/server.hcl
  server {
    enabled = true
    bootstrap_expect = 1
  }

  data_dir = "/opt/nomad"
  bind_addr = "0.0.0.0"
  log_level = "INFO"

  acl {
    enabled = true
    token_ttl = "30m"
    policy_ttl = "30m"
  }
  EOF
- nohup nomad agent -config=/etc/nomad.d > /var/log/nomad.log 2>&1 &
