name: Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Init
        run: terraform -chdir=infra/environments/dev init

      - name: Validate
        run: terraform -chdir=infra/environments/dev validate

      - name: Plan
        run: terraform -chdir=infra/environments/dev plan
